/* eslint-disable prettier/prettier */
import type { ChatMessage, Citation } from "@/types";
import { parseMarkdown } from "./markdownParser";
import type { ExportDocument } from "./types";

const MAX_NAME = 60;

export const slugify = (input: string) =>
  input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, MAX_NAME) || "itl-ai-response";

export const formatTimestamp = (iso?: string) => {
  const d = iso ? new Date(iso) : new Date();
  const safe = Number.isNaN(d.getTime()) ? new Date() : d;
  return safe.toLocaleString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
};

const DISCLAIMER =
  "This document was generated by ITL AI from the sources cited above. It is provided for professional reference only and does not constitute legal or tax advice. Verify all citations against the original statute, notification or judgement before relying on them.";

/**
 * Assembles the full, renderer-agnostic document for one assistant message.
 * Both exporters take this object — nothing here knows about jsPDF or docx.
 */
export function buildExportDocument(opts: {
  message: ChatMessage;
  question?: string;
  subtitle?: string;
}): ExportDocument {
  const { message, question, subtitle = "AI Research Response" } = opts;

  const sources = (message.citations ?? []).map((c: Citation) => ({
    label: c.heading,
    documentType: c.documentType,
    link: c.link,
    snippet: c.snippet,
  }));

  const stamp = new Date(message.createdAt ?? Date.now());
  const datePart = (Number.isNaN(stamp.getTime()) ? new Date() : stamp).toISOString().slice(0, 10);

  return {
    brand: "ITL AI",
    subtitle,
    generatedAt: formatTimestamp(message.createdAt),
    question: question?.trim() || undefined,
    body: parseMarkdown(message.content ?? ""),
    sources: sources.length ? sources : undefined,
    disclaimer: DISCLAIMER,
    fileName: `itl-ai-${slugify(question || subtitle)}-${datePart}`,
  };
}
